type: object
properties:
  client_name:
    type: string
    description: The client name.
  alert_date:
    type: string
    description: The date of the alert.
  sku_code:
    type: string
    description: The SKU code.
  sku_description:
    type: string
    description: The SKU name.
  retailer:
    type: string
    description: The retailer name.
  store_id:
    type: string
    description: The store ID.
  store_description:
    type: string
    description: The store name.
  action:
    type: string
    description: The action.
  action_description:
    type: string
    description: The action description.
example:
  client_name: myCompany
  alert_date: 2022-08-15T23:00:00.000Z
  sku_code: 33453
  sku_description: 33453 - myCompany greatProduct
  retailer: tesco
  store_id: 1111
  store_description: 3322 London
  action: no_sales
  action_description: No sales recorded for this SKU in 4 weeks